# generate-media.ps1
# Scans /media for image, audio, and video files and adds any new
# ones to media-data.js, preserving already-recorded entries and
# their original timestamps. Runs automatically from publish.bat —
# you shouldn't need to run this by hand.

$mediaDir = Join-Path $PSScriptRoot "media"
$outputFile = Join-Path $PSScriptRoot "media-data.js"

$imageExts = @(".jpg", ".jpeg", ".png", ".gif", ".webp")
$audioExts = @(".mp3", ".wav", ".m4a", ".ogg")
$videoExts = @(".mp4", ".mov", ".webm")

function Get-MediaType($ext) {
    if ($imageExts -contains $ext) { return "image" }
    if ($audioExts -contains $ext) { return "audio" }
    if ($videoExts -contains $ext) { return "video" }
    return $null
}

# Read existing entries so already-recorded timestamps don't change
$existingFiles = @{}
$existingEntriesText = ""
if (Test-Path $outputFile) {
    $content = Get-Content $outputFile -Raw
    $idMatches = [regex]::Matches($content, '(?s)\{\s*id:\s*"([^"]+)".*?\}')
    foreach ($m in $idMatches) {
        $existingFiles[$m.Groups[1].Value] = $true
    }
    $bodyMatch = [regex]::Match($content, '(?s)const media = \[(.*)\];')
    if ($bodyMatch.Success) {
        $existingEntriesText = $bodyMatch.Groups[1].Value.Trim()
    }
}

# Find files in /media not already recorded
$newEntries = @()
if (Test-Path $mediaDir) {
    Get-ChildItem $mediaDir -File | ForEach-Object {
        $ext = $_.Extension.ToLower()
        $type = Get-MediaType $ext
        if ($type -and -not $existingFiles.ContainsKey($_.Name)) {
            $timestamp = $_.CreationTime.ToString("yyyy-MM-ddTHH:mm:ss")
            $entry = "  { id: ""$($_.Name)"", file: ""media/$($_.Name)"", type: ""$type"", timestamp: ""$timestamp"" }"
            $newEntries += $entry
        }
    }
}

if ($newEntries.Count -eq 0 -and $existingEntriesText -eq "") {
    Write-Host "No media files found yet."
} elseif ($newEntries.Count -eq 0) {
    Write-Host "No new media files found."
} else {
    Write-Host "Found $($newEntries.Count) new media file(s)."
}

$allEntriesText = ($newEntries -join ",`r`n")
if ($existingEntriesText -ne "") {
    if ($newEntries.Count -gt 0) {
        $allEntriesText = $allEntriesText + ",`r`n" + $existingEntriesText
    } else {
        $allEntriesText = $existingEntriesText
    }
}

$header = "// AUTO-GENERATED by generate-media.ps1 -- do not hand-edit directly.`r`n// Runs automatically each time you double-click publish.bat.`r`n// Add photos, audio, or video files to /media and they'll appear`r`n// here automatically the next time you publish.`r`n`r`nconst media = [`r`n"
$footer = "`r`n];`r`n"

Set-Content -Path $outputFile -Value ($header + $allEntriesText + $footer) -Encoding UTF8
