// AUTO-GENERATED by generate-media.ps1 -- do not hand-edit directly.
// Runs automatically each time you double-click publish.bat.
// Add photos, audio, or video files to /photos and they'll appear
// here automatically the next time you publish.

const media = [
  { id: "Call to Prayer 9.23.mp3", file: "photos/Call to Prayer 9.23.mp3", type: "audio", timestamp: "2026-09-23T06:48:18" },
{ id: "IMG_5312.JPG", file: "photos/IMG_5312.JPG", type: "image", timestamp: "2026-09-22T06:26:26" },
  { id: "IMG_5314.JPG", file: "photos/IMG_5314.JPG", type: "image", timestamp: "2026-09-22T06:26:26" },
{ id: "englishcorner.JPG", file: "photos/englishcorner.JPG", type: "image", timestamp: "2026-09-21T18:24:48" },
  { id: "example.jpg", file: "photos/example.jpg", type: "image", timestamp: "2026-09-03T00:11:44" },
  { id: "IMG_4349.jpg", file: "photos/IMG_4349.jpg", type: "image", timestamp: "2026-09-04T19:57:35" },
  { id: "IMG_4583.jpg", file: "photos/IMG_4583.jpg", type: "image", timestamp: "2026-09-07T20:59:19" },
  { id: "IMG_4673.jpg", file: "photos/IMG_4673.jpg", type: "image", timestamp: "2026-09-07T20:59:19" },
  { id: "IMG_4795.jpg", file: "photos/IMG_4795.jpg", type: "image", timestamp: "2026-09-07T20:59:19" },
  { id: "IMG_4820.jpg", file: "photos/IMG_4820.jpg", type: "image", timestamp: "2026-09-07T20:59:19" },
  { id: "IMG_5064.jpg", file: "photos/IMG_5064.jpg", type: "image", timestamp: "2026-09-15T20:31:53" },
  { id: "IMG_5085.jpg", file: "photos/IMG_5085.jpg", type: "image", timestamp: "2026-09-15T20:31:24" },
  { id: "IMG_5115.jpg", file: "photos/IMG_5115.jpg", type: "image", timestamp: "2026-09-20T22:41:02" },
  { id: "IMG_5115.jpg.jpeg", file: "photos/IMG_5115.jpg.jpeg", type: "image", timestamp: "2026-09-20T22:18:35" },
  { id: "IMG_5142.jpg", file: "photos/IMG_5142.jpg", type: "image", timestamp: "2026-09-20T22:41:02" },
  { id: "IMG_5142.jpg.jpeg", file: "photos/IMG_5142.jpg.jpeg", type: "image", timestamp: "2026-09-20T22:18:58" },
  { id: "IMG_5206 Large.jpeg", file: "photos/IMG_5206 Large.jpeg", type: "image", timestamp: "2026-09-20T22:18:35" },
  { id: "IMG_5225.jpg", file: "photos/IMG_5225.jpg", type: "image", timestamp: "2026-09-20T22:41:02" },
  { id: "IMG_5226.jpg", file: "photos/IMG_5226.jpg", type: "image", timestamp: "2026-09-20T22:34:48" },
  { id: "IMG_5235 Large.jpeg", file: "photos/IMG_5235 Large.jpeg", type: "image", timestamp: "2026-09-20T22:18:35" },
  { id: "squat-toilet.jpg", file: "photos/squat-toilet.jpg", type: "image", timestamp: "2026-09-15T20:28:16" }
];

